### ISSUE TITLE
Default speed assignment

### ISSUE THREAD

**Issue by littlecommie** [tbertrand7/TTE_Solutions#10]
The default speed in the track model DB should be -1, so that I can distinguish between a speed command of 0 and an unassigned speed. So Daxton should either set the default to -1, or Alisha needs to set each speed on a valid path to -1.

**Comment by thatDaxton** [comment]
Can do! Look for this tonight or tomorrow afternoon!

**Comment by thatDaxton** [comment]
Change is live and working, reset db now adds -1 as the default speed.

**Comment by littlecommie** [comment]
Thanks!
