### ISSUE TITLE
Track Model Station Name Bug

### ISSUE THREAD

**Issue by tbertrand7** [tbertrand7/TTE_Solutions#18]
When viewing block info in track model, the first letter of every station name is cut off.

I think both ctc and track model should agree on the format of infrastructure strings to avoid any more bugs between subsystems regarding infrastructure info being displayed/modified.

**Comment by thatDaxton** [comment]
This bug was introduced when the database was restructured to not have spaces in between semicolons and station names. Change has been made and will be pushed shortly
