### ISSUE TITLE
Elevation Conversion Bug

### ISSUE THREAD

**Issue by tbertrand7** [tbertrand7/TTE_Solutions#22]
It seems that the value being stored in the db for track elevation is not being converted properly from meters to feet.

For example:
Green Line Block 2:
Elevation is 1m but it is being stored as 10.76 ft instead of 3.28 ft

Other values appear to be fine.

**Comment by tbertrand7** [comment]
Not sure if this also affects cumulative elevation since my module does not look at this

**Comment by thatDaxton** [comment]
Looks like its hard coded to that value in the reset script, I will change it to 3.28ft if that is the correct value.

**Comment by thatDaxton** [comment]
Can someone verify that 32.29173125 is the correct value for Green 3

**Comment by tbertrand7** [comment]
I believe they all could be incorrect. Green line blocks 1-3 were all incorrect. Didn't check all of them.

**Comment by tbertrand7** [comment]
I believe they all could be incorrect. Green line blocks 1-3 were all incorrect. Didn't check any more however.

**Comment by thatDaxton** [comment]
Great.

**Comment by thatDaxton** [comment]
Yet conversions were wrong have been since the third week of class when we did it.

**Comment by tbertrand7** [comment]
I mean I guess if they were hard coded everyone just assumed the values were right.
