### ISSUE TITLE
Switch Class

### ISSUE THREAD

**Issue by tbertrand7** [tbertrand7/TTE_Solutions#3]
I think we should create a class for a switch that contains the following data:

Switch ID
Block Switch is located on
Current Switch Position
The two possible switch positions

A method should be a toggle method that switches the current switch position between the two possible positions.

I think this would help prevent communication issues between the modules and prevent switches from being set to incorrect states.

**Comment by thatDaxton** [comment]
There is a switch class now, I am not sure what alisha wants to do with it fully so I will close this for the time being.
